set_device_property:
  name: Set Device Properties
  description: "Set the properties of a Mitsubishi HVAC device."
  fields:
    climate_entity:
      description: "Select the target climate entity."
      required: true
      selector:
        entity:
          filter:
            integration: mhi_hvac
            domain: climate
          multiple: true
    hvac_mode:
      description: "Set the HVAC mode."
      required: false
      selector:
        select:
          options:
            - value: cool
              label: Cool
            - value: dry
              label: Dry
            - value: fan_only
              label: Fan Only
            - value: heat
              label: Heat
          mode: dropdown
    onoff_mode:
      description: "Set the on/off mode."
      required: false
      selector:
        select:
          options:
            - value: on
              label: On
            - value: off
              label: Off
          mode: list
    target_temperature:
      description: "Specify the target temperature (within the device's allowed range)."
      required: false
      selector:
        number:
          min: 18
          max: 30
          step: 0.5
          mode: box
          unit_of_measurement: "°C"
    fan_mode:
      description: "Set the fan mode."
      required: false
      selector:
        select:
          options:
            - value: low
              label: Low
            - value: medium
              label: Medium
            - value: high
              label: High
            - value: diffuse
              label: Diffuse
          mode: dropdown
    swing_mode:
      description: "Set the swing mode."
      required: false
      selector:
        select:
          options:
            - value: auto
              label: Auto
            - value: stop1
              label: Stop1
            - value: stop2
              label: Stop2
            - value: stop3
              label: Stop3
            - value: stop4
              label: Stop4
          mode: dropdown
    filter_reset:
      description: "Reset the filter sign."
      required: false
      selector:
        boolean:
    lock_mode:
      description: "Set the lock mode."
      required: false
      selector:
        select:
          options:
            - value: locked
              label: Locked
            - value: locked_onoff
              label: On/Off
            - value: locked_mode
              label: Mode
            - value: locked_temp
              label: Temperature
            - value: locked_onoff_mode
              label: On/Off + Mode
            - value: locked_onoff_temp
              label: On/Off + Temperature
            - value: locked_mode_temp
              label: Mode + Temperature
            - value: unlocked
              label: Unlocked
          mode: dropdown

set_active_hvac_modes:
  name: Set Active HVAC modes
  description: "Set the active HVAC modes of a Mitsubishi HVAC device."
  fields:
    config_entry_id:
      description: "The Config Entry for the Mitsubishi HVAC device."
      required: true
      selector:
        config_entry:
          integration: mhi_hvac
    new_active_mode:
      description: "The new HVAC modes for the Mitsubishi HVAC device."
      required: true
      selector:
        text: