set_device_property:
  name: Set Device Properties
  description: Set the properties of a Mitsubishi HVAC device.
  fields:
    climate_entity:
      name: Climate Entity
      description: Select the target climate entity. If the selected climate entity is a group, the property/ies will be set to all the units of the group.
      required: true
      selector:
        entity:
          filter:
            integration: mhi_hvac
            domain: climate
          multiple: true
    hvac_mode:
      name: HVAC Mode
      description: Set the HVAC mode. The running state of the unit will not be changed unless specified in the On/Off mode.
      required: false
      selector:
        select:
          options:
            - value: cool
              label: Cool
            - value: dry
              label: Dry
            - value: fan_only
              label: Fan Only
            - value: heat
              label: Heat
          mode: dropdown
    onoff_mode:
      name: On/Off Mode
      description: Set the on/off mode.
      required: false
      selector:
        select:
          options:
            - value: "on"
              label: On
            - value: "off"
              label: Off
          mode: list
    target_temperature:
      name: Target Temperature
      description: Specify the target temperature (within the device's allowed range).
      required: false
      selector:
        number:
          min: 18
          max: 30
          step: 0.5
          mode: box
          unit_of_measurement: "°C"
    fan_mode:
      name: Fan Mode
      description: Set the fan mode.
      required: false
      selector:
        select:
          options:
            - value: low
              label: Low
            - value: medium
              label: Medium
            - value: high
              label: High
            - value: diffuse
              label: Diffuse
          mode: dropdown
    swing_mode:
      name: Swing Mode
      description: Set the swing mode.
      required: false
      selector:
        select:
          options:
            - value: auto
              label: Auto
            - value: stop1
              label: Stop1
            - value: stop2
              label: Stop2
            - value: stop3
              label: Stop3
            - value: stop4
              label: Stop4
          mode: dropdown
    filter_reset:
      name: Reset Filter
      description: Reset the filter signal to clean.
      required: false
      selector:
        boolean:
    lock_mode:
      name: Lock Mode
      description: Set the lock mode of the Remote Control.
      required: false
      selector:
        select:
          options:
            - value: locked
              label: Locked
            - value: locked_onoff
              label: On/Off
            - value: locked_mode
              label: Mode
            - value: locked_temp
              label: Temperature
            - value: locked_onoff_mode
              label: On/Off + Mode
            - value: locked_onoff_temp
              label: On/Off + Temperature
            - value: locked_mode_temp
              label: Mode + Temperature
            - value: unlocked
              label: Unlocked
          mode: dropdown

set_active_hvac_modes:
  name: Set Active HVAC modes
  description: If the HVAC modes have been configured it will set the active (valid) HVAC modes.
  fields:
    config_entry_id:
      name: Device
      description: The MHI HVAC device.
      required: true
      selector:
        config_entry:
          integration: mhi_hvac
    new_active_mode:
      name: New HVAC modes
      description: The new HVAC modes for the MHI HVAC device.
      required: true
      selector:
        text:
